### ISSUE TITLE
Unable to open Gitify on Pop!_OS 22.04

### ISSUE THREAD

**Issue by boundless-forest** [gitify-app/gitify#1612]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

I discovered Gitify this afternoon and attempted to install the deb version on PopOS first, which installed successfully. However, when I click the icon, the Gitify window does not open. The icon appears in the system bar, but there is no response when clicked.

![image](https://github.com/user-attachments/assets/3bd7cb34-919d-4d96-97df-4e549a490bb8)

I checked the process info like this:

```sh
bear@pop-os ~/Downloads> ps aux | grep gitify
bear      123381  2.8  0.6 1212191996 153208 ?   SNl  16:59   0:00 /opt/Gitify/gitify
bear      123388  0.1  0.2 33816956 51840 ?      SN   16:59   0:00 /opt/Gitify/gitify --type=zygote --no-zygote-sandbox
bear      123389  0.0  0.2 33816940 51840 ?      SN   16:59   0:00 /opt/Gitify/gitify --type=zygote
bear      123391  0.0  0.0 33816940 10656 ?      SN   16:59   0:00 /opt/Gitify/gitify --type=zygote
bear      123418  2.3  0.6 34321032 161188 ?     SNl  16:59   0:00 /opt/Gitify/gitify --type=gpu-process --enable-crash-reporter=a4b59d2d-2696-4de5-9e0c-b3e5031a8baf,no_channel --user-data-dir=/home/bear/.config/gitify --gpu-preferences=UAAAAAAAAAAgAAAEAAAAAAAAAAAAAAAAAABgAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAABAAAAAAAAAAEAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --shared-files --field-trial-handle=3,i,1101294913920176142,9749069726429956090,262144 --disable-features=SpareRendererForSitePerProcess --variations-seed-version
bear      123422  0.1  0.2 33882968 67200 ?      SNl  16:59   0:00 /opt/Gitify/gitify --type=utility --utility-sub-type=network.mojom.NetworkService --lang --service-sandbox-type=none --enable-crash-reporter=a4b59d2d-2696-4de5-9e0c-b3e5031a8baf,no_channel --user-data-dir=/home/bear/.config/gitify --shared-files=v8_context_snapshot_data:100 --field-trial-handle=3,i,1101294913920176142,9749069726429956090,262144 --disable-features=SpareRendererForSitePerProcess --variations-seed-version
bear      123433  1.5  0.5 1212041756 141748 ?   SNl  16:59   0:00 /opt/Gitify/gitify --type=renderer --enable-crash-reporter=a4b59d2d-2696-4de5-9e0c-b3e5031a8baf,no_channel --user-data-dir=/home/bear/.config/gitify --app-path=/opt/Gitify/resources/app.asar --no-sandbox --no-zygote --lang --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=4 --time-ticks-at-unix-epoch=-1730163822039494 --launch-time-ticks=28540830037 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=3,i,1101294913920176142,9749069726429956090,262144 --disable-features=SpareRendererForSitePerProcess --variations-seed-version
bear      123697  0.0  0.0  19016  2688 pts/2    SN+  16:59   0:00 grep --color=auto gitify

```

I guess AppImage might work, so I’ll give it a try, but no luck. The Gitify window still hasn’t popped up.

The AppImage console output:
```sh
14:58:10.708 › Electron's autoUpdater does not support the 'linux' platform. Ref: https://www.electronjs.org/docs/latest/api/auto-updater#platform-notices
```

I'm not sure what to do next; perhaps there's a way to output a debug log?

### 🪜 Steps To Reproduce

1. Download the appImage or deb version
2. Run it

### Gitify Version

5.16.1

### Operating System

PopOs 22.04

**Comment by bmulholland** [comment]
There's not enough information included in this Issue for us to act on it:
1. The message you quote is expected, and is an upstream issue anyway. It wouldn't block Gitify from working, just from automatically upgrading.
2. If Gitify truly isn't working, you'll need to include what isn't working and why. As Linux setups vary widely, we can't feasibly reproduce your error, so you'll either need to provide repro steps or do significant debugging on your own.

In general, filing Issues saying simply "not works" isn't a good use of anyone's time, for any project. If you're unsure about your English, there's more than enough LLMs out there to help you translate. They could also guide you through common debugging steps, and suggest what you could do to fill out an effective bug report.

Happy to re-open this if sufficiently more information is provided later.

**Comment by boundless-forest** [comment]
I sincerely apologize for my informal description of the issue. I have added more details to it; would you mind reviewing it again? Please feel free to ask me for any additional information if needed. @bmulholland

**Comment by bmulholland** [comment]
Much better, thank you!

**Comment by setchy** [comment]
@boundless-forest if possible, I'd be interested to hear your experience running Gitify from source code on your PopOS machine. Does that work?

**Comment by boundless-forest** [comment]
I'm stuck at the first step when installing dependencies; it reports the following error, indicating something unexpected in the post-install script.

```sh
⋊> ~/w/gitify on main ◦ pnpm install                                                                                                                                                                                                                                              13:58:56
Lockfile is up to date, resolution step is skipped
Packages: +2 -20
++--------------------
Progress: resolved 0, reused 21, downloaded 1, added 2, done
node_modules/electron: Running postinstall script, failed in 2m 15.9s
node_modules/electron postinstall$ node install.js
│ RequestError
│     at ClientRequest.<anonymous> (/home/bear/working-on/gitify/node_modules/got/dist/source/core/index.js:970:111)
│     at Object.onceWrapper (node:events:622:26)
│     at ClientRequest.emit (node:events:519:35)
│     at origin.emit (/home/bear/working-on/gitify/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
│     at emitErrorEvent (node:_http_client:103:11)
│     at TLSSocket.socketErrorListener (node:_http_client:506:5)
│     at TLSSocket.emit (node:events:507:28)
│     at emitErrorNT (node:internal/streams/destroy:170:8)
│     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
│     at process.processTicksAndRejections (node:internal/process/task_queues:90:21)AggregateError [ETIMEDOUT]: 
│     at internalConnectMultiple (node:net:1128:18)
│     at afterConnectMultiple (node:net:1693:7)
└─ Failed in 2m 15.9s at /home/bear/working-on/gitify/node_modules/electron
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by bmulholland** [comment]
Yeah, env issues can be frustrating! Let us know when you've worked through issues installing electron etc and have details on running Gitify itself.

**Comment by farfromrefug** [comment]
ACtually i have the exact same issue on PopOS 22.04. The tray appear but does not react to click (left/right).
i tried to build locally and run and got the same error. Not sure how to debug this. Must be related to the lib used for tray icons in Electron.
I see some issues in electron repo https://github.com/electron/electron/issues/37112. The issue must be related to libayatana-appindicator. WHat i can say is that it works with my fork using tauri. So it does not seem to be related to ubuntu setup/config

**Comment by ronilaukkarinen** [comment]
I have this same issue. Can't be used right now on Pop!_OS.

**Comment by setchy** [comment]
Curious if any of you have tried downgrading Gitify. I'm interested in what is the latest working version

**Comment by boundless-forest** [comment]
![image](https://github.com/user-attachments/assets/c051d596-f7bc-4484-bf88-a411f211b446)

I did a test with those versions, neither of them works, but I noticed a strange log in the installation, not sure if it's helpful.

```sh
⋊> ~/Downloads sudo dpkg -i gitify_5.10.0_amd64.deb                                                                                                                                                                                                                               13:49:46
dpkg: warning: downgrading gitify from 5.17.0 to 5.10.0
(Reading database ... 235664 files and directories currently installed.)
Preparing to unpack gitify_5.10.0_amd64.deb ...
Unpacking gitify (5.10.0) over (5.17.0) ...
Setting up gitify (5.10.0) ...
update-alternatives is /usr/bin/update-alternatives
Could not parse file "/usr/share/applications/guake.desktop": No such file or directory  // this line
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
```

**Comment by setchy** [comment]
Thanks @boundless-forest 

So to confirm my understanding, these versions were tested and found incompatible with PopOS
- `v4.4.0`
- `v5.0.0`
- `v5.5.0`
- `v5.10.0`
- `v5.15.0`
- `v5.17.0`

Re: the `autoUpdater` log entry, that is expected - https://github.com/electron/update.electronjs.org only supports Windows and macOS currently

**Comment by boundless-forest** [comment]
Yes, it's a bit strange that I noticed from the GitHub issues that Gitify appears to work on other Linux platforms except Pop!_OS. However, since Pop!_OS is based on Ubuntu, it should function properly as well. I have researched this issue extensively but have not found a workaround. Do you have any suggestions?

**Comment by setchy** [comment]
> Do you have any suggestions?

I'd continue to debug the logic within https://github.com/gitify-app/gitify/blob/main/src/main/main.ts, which controls showing/hiding the main window with the help of the package https://github.com/max-mapper/menubar

**Comment by boundless-forest** [comment]
I'm here if anything that I can help. Please tell me.

**Comment by setchy** [comment]
> I'm here if anything that I can help. Please tell me.

Thank you. As above, I'd recommend continuing to debug those areas. The maintainers don't have readily access to an environment to reproduce atm

**Comment by nachog00** [comment]
Im getting a similar problem, even though for me, the window does appear very briefly and dissapears. It did appear alright when i first logged in tho.
I'm not on PopOs.

OS    ➜  Arch Linux x86_64
 ├   ➜  Linux 6.12.4-arch1-1
 └   ➜  bash 5.2.37

WM    ➜  Hyprland (Wayland)
 ├ 󰀻  ➜  Papirus [GTK2/3]
 ├   ➜  Bibata-Modern-Ice (24px)
 ├   ➜  zellij 0.41.2

**Comment by hazemadelkhalel** [comment]
I have the same issue, After installing the .deb file when I tried to open the application the icon only appeared in the top bar but didn't appear.

I am using Ubuntu 22.04.5 LTS

**Comment by setchy** [comment]
> I have the same issue, After installing the `gitify_5.18.0_amd64.deb` file when I tried to open the application the icon only appeared in the top bar but didn't appear.
> 
> I am using Ubuntu 22.04.5 LTS

I have an Ubuntu 24.04.1 LTS VM and was able to verify both 5.18.0 running and the upcoming 6.0.0 release

To install and run gitify I had to do a few steps

**Install**
```
sudo apt install /tmp/gitify-installers/gitify_5.18.0_amd64.deb
```

**First Launch**
The app did not launch for the first time.  

Running `gitify` via the terminal or checking the output of `journalctl -xe | grep gitify` unveiled permission issues re: chrome-sandbox

**Fix Chrome Sandbox permissions**
Running the below to fix the permissions for the chrome sandbox
```
sudo chown root:root /opt/Gitify/chrome-sandbox
sudo chown 4755 /opt/Gitify/chrome-sandbox
```

**Success**
|5.18.0|6.0.0|
|---|---|
| ![Image](https://github.com/user-attachments/assets/c2688b93-6128-43d3-ba21-5657e2cefd13) | ![Image](https://github.com/user-attachments/assets/f6428df8-b525-4175-9bad-7d9e020494f5) |



I don't have a PopOS VM

**Comment by hazemadelkhalel** [comment]
I have followed all the steps you provided, but it still doesn’t work. I encountered the same permission issue you mentioned and executed the commands you suggested. However, even after doing so, the problem persists. I killed the process and restarted it, but the issue remains unchanged. I also restarted the machine, but unfortunately, the result is still the same.

``journalctl -xe | grep gitify`` this doesn't show anything

should I wait for the next release?

**Comment by setchy** [comment]
> should I wait for the next release?

you're welcome to report back with v6.0.0, but there isn't any specific changes related to this.  I tested all releases from v5.12.1 through to v6.0.0 this morning on Ubuntu and they worked on my test machine.  

To resolve this for other users like yourself, I'll need further community assistance with debugging.

**Comment by hazemadelkhalel** [comment]
I tried your steps and still, and the error still happening with me, I tried to run without sandbox 
using
`` sudo gitify --no-sandbox ``

and it seems to run

![Image](https://github.com/user-attachments/assets/2099af3d-57cc-48a3-bc63-edc1f2bc4077)


and this is the error
```bash
[41615:0202/215127.649577:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.649639:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.649654:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.649668:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.649683:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.NameHasOwner: object_path= /org/freedesktop/DBus: unknown error type: 
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[41615:0202/215127.662262:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.681272:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.695278:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.NameHasOwner: object_path= /org/freedesktop/DBus: unknown error type: 
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[41781:0202/215127.695730:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[41781:0202/215127.695831:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[41781:0202/215127.695882:ERROR:gl_display.cc(762)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
Authorization required, but no authorization protocol specified
[41781:0202/215127.696037:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[41781:0202/215127.696082:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[41781:0202/215127.696112:ERROR:gl_display.cc(762)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[41781:0202/215127.696141:ERROR:gl_display.cc(796)] Initialization of all EGL display types failed.
[41781:0202/215127.696172:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
Authorization required, but no authorization protocol specified
[41781:0202/215127.715562:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[41781:0202/215127.715665:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[41781:0202/215127.715748:ERROR:gl_display.cc(762)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
Authorization required, but no authorization protocol specified
[41781:0202/215127.716102:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[41781:0202/215127.716138:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[41781:0202/215127.716164:ERROR:gl_display.cc(762)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[41781:0202/215127.716189:ERROR:gl_display.cc(796)] Initialization of all EGL display types failed.
[41781:0202/215127.716213:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[41781:0202/215127.717006:ERROR:viz_main_impl.cc(185)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[41816:0202/215127.780113:ERROR:angle_platform_impl.cc(44)] DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
[41816:0202/215127.780276:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[41816:0202/215127.780325:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Not initialized.
[41816:0202/215127.780355:ERROR:gl_display.cc(762)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[41816:0202/215127.780392:ERROR:gl_display.cc(796)] Initialization of all EGL display types failed.
[41816:0202/215127.780423:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
Authorization required, but no authorization protocol specified
[41816:0202/215127.812559:ERROR:angle_platform_impl.cc(44)] DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
[41816:0202/215127.812655:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[41816:0202/215127.812759:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Not initialized.
[41816:0202/215127.812801:ERROR:gl_display.cc(762)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[41816:0202/215127.812836:ERROR:gl_display.cc(796)] Initialization of all EGL display types failed.
[41816:0202/215127.812870:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[41816:0202/215127.814657:ERROR:viz_main_impl.cc(185)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[41826:0202/215127.859661:ERROR:x11_software_bitmap_presenter.cc(150)] XGetWindowAttributes failed for window 102760452
```

**Comment by hazemadelkhalel** [comment]
### **Issue:**
After running ``sudo gitify --no-sandbox`` and debugging with  @BemwaMalak, the following errors were encountered:

```
[41615:0202/215127.649577:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.649639:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.649654:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.649668:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.649683:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.NameHasOwner: object_path= /org/freedesktop/DBus: unknown error type: 
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[41615:0202/215127.662262:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.681272:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.695278:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.NameHasOwner: object_path= /org/freedesktop/DBus: unknown error type: 
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[41781:0202/215127.695730:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[41781:0202/215127.695831:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[41781:0202/215127.695882:ERROR:gl_display.cc(762)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
Authorization required, but no authorization protocol specified
[41781:0202/215127.696037:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[41781:0202/215127.696082:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[41781:0202/215127.696112:ERROR:gl_display.cc(762)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[41781:0202/215127.696141:ERROR:gl_display.cc(796)] Initialization of all EGL display types failed.
[41781:0202/215127.696172:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
Authorization required, but no authorization protocol specified
[41781:0202/215127.715562:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[41781:0202/215127.715665:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[41781:0202/215127.715748:ERROR:gl_display.cc(762)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
Authorization required, but no authorization protocol specified
[41781:0202/215127.716102:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[41781:0202/215127.716138:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[41781:0202/215127.716164:ERROR:gl_display.cc(762)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[41781:0202/215127.716189:ERROR:gl_display.cc(796)] Initialization of all EGL display types failed.
[41781:0202/215127.716213:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[41781:0202/215127.717006:ERROR:viz_main_impl.cc(185)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[41816:0202/215127.780113:ERROR:angle_platform_impl.cc(44)] DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
[41816:0202/215127.780276:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[41816:0202/215127.780325:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Not initialized.
[41816:0202/215127.780355:ERROR:gl_display.cc(762)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[41816:0202/215127.780392:ERROR:gl_display.cc(796)] Initialization of all EGL display types failed.
[41816:0202/215127.780423:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
Authorization required, but no authorization protocol specified
[41816:0202/215127.812559:ERROR:angle_platform_impl.cc(44)] DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
[41816:0202/215127.812655:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[41816:0202/215127.812759:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Not initialized.
[41816:0202/215127.812801:ERROR:gl_display.cc(762)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[41816:0202/215127.812836:ERROR:gl_display.cc(796)] Initialization of all EGL display types failed.
[41816:0202/215127.812870:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[41816:0202/215127.814657:ERROR:viz_main_impl.cc(185)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[41826:0202/215127.859661:ERROR:x11_software_bitmap_presenter.cc(150)] XGetWindowAttributes failed for window 102760452
```

### **Diagnosis:**
The errors indicate that the application is unable to connect to the X11 display server and the D-Bus message bus. This is likely due to missing or improperly configured dependencies related to the graphical environment (X11) and D-Bus.

### **Solution:**
The issue was resolved by installing the dbus-x11 package, which provides the necessary D-Bus integration for X11 environments. To fix this, run the following command:

```
sudo apt-get install dbus-x11
```

This package ensures that the application can properly communicate with the X11 display server and D-Bus, resolving the errors related to display initialization and authorization.

### **Additional Notes**:
If you are using a different desktop environment or display server (e.g., Wayland), you may need to install additional packages or configure your environment accordingly. For example, Wayland users might need to install wayland or weston packages.

If the issue persists after installing dbus-x11, ensure that your X11 server is running and properly configured. You can also try running the application with the --no-sandbox flag as a temporary workaround, though this is not recommended for long-term use due to security implications.

**Comment by boundless-forest** [comment]
Update: I tried it in Ubuntu 24.04 Wayland, but it doesn't work either.

```sh
[41615:0202/215127.649577:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.649639:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.649654:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.649668:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[41615:0202/215127.649683:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.NameHasOwner: object_path= /org/freedesktop/DBus: unknown error type: 
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
```

**Comment by setchy** [comment]
@boundless-forest - hope all is well. Just wondering if this is still occurring with the latest release v6.4.1

**Comment by herder** [comment]
> [@boundless-forest](https://github.com/boundless-forest) - hope all is well. Just wondering if this is still occurring with the latest release v6.4.1

I just tried the latest release on PopOs 24.04 Wayland, and the problem is still there. The app goes to the tray but can't be opened at all.

**Comment by setchy** [comment]
Thanks for testing, @herder

**Comment by khssnv** [comment]
Same (icon in the tray, no window) with AppImage on Ubuntu 25.04.

**Comment by setchy** [comment]
https://github.com/max-mapper/menubar/issues/491

**Comment by setchy** [comment]
I had a few minutes this afternoon so tried installing Gitify v6.10.0 on Ubuntu 24.04 in a virtual machine.  

Gitify was able to run, though I did note that in order for the window to open I had to double click (not single click) on the taskbar icon.
