### ISSUE TITLE
Not able to run the app on linux

### ISSUE THREAD

**Issue by anjannath** [gitify-app/gitify#341]
This is the error i get, i don't know java but would like to use this app, since electron is cross platform, i expected it to work on linux as well.

/cc @manosim 

```
[gitify]$ npm start

> gitify@2.0.2 start /home/anjan/github.com/gitify
> electron . –enable-logging

App threw an error during load
TypeError: Cannot read property '0' of null
    at Object.<anonymous> (/home/anjan/github.com/gitify/main.js:20:43)
    at Object.<anonymous> (/home/anjan/github.com/gitify/main.js:210:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (/home/anjan/github.com/gitify/node_modules/electron/dist/resources/default_app.asar/main.js:283:12)
    at Object.<anonymous> (/home/anjan/github.com/gitify/node_modules/electron/dist/resources/default_app.asar/main.js:325:5)
    at Object.<anonymous> (/home/anjan/github.com/gitify/node_modules/electron/dist/resources/default_app.asar/main.js:361:3)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property '0' of null
    at Object.<anonymous> (/home/anjan/github.com/gitify/main.js:20:43)
    at Object.<anonymous> (/home/anjan/github.com/gitify/main.js:210:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (/home/anjan/github.com/gitify/node_modules/electron/dist/resources/default_app.asar/main.js:283:12)
    at Object.<anonymous> (/home/anjan/github.com/gitify/node_modules/electron/dist/resources/default_app.asar/main.js:325:5)
    at Object.<anonymous> (/home/anjan/github.com/gitify/node_modules/electron/dist/resources/default_app.asar/main.js:361:3)
^C[gitify]$ node --version
v8.11.3

```

**Comment by orsonteodoro** [comment]
You can comment out or delete that line found at https://github.com/manosim/gitify/blob/7a7c45857cb945470f64b9888b69a842562e122e/main.js#L20 .

The alternative solution is to put a conditional check for isDarwin before assigning the value to that value or process.execPath.

**Comment by bmulholland** [comment]
Closing as stale, please open a new issue if it's still happening
